[package]
name = "packsmith-cli"
description = "The packsmith command line interface."
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "packsmith"
path = "src/main.rs"

[dependencies]
packsmith-compiler = { path = "../packsmith-compiler" }
packsmith-emit = { path = "../packsmith-emit" }
packsmith-mcversion = { path = "../packsmith-mcversion" }
serde_json = { workspace = true }
