[package]
name = "packsmith-emit"
description = "IR to file tree to deterministic zip."
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
packsmith-ir = { workspace = true }
packsmith-mcversion = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
